# Generated by Django 3.2.8 on 2022-10-04 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchFilterWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_weight', models.CharField(max_length=100)),
                ('search_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_weights', to='api.searchfilter')),
            ],
        ),
        migrations.CreateModel(
            name='SearchFilterParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('select', 'Select Box')], default='text', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('search_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.searchfilter')),
            ],
        ),
    ]
