# Generated by Django 3.2.8 on 2022-10-04 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_string', models.CharField(default='', max_length=50)),
                ('user_id', models.IntegerField()),
                ('useremail', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=30)),
                ('contact_id', models.IntegerField(blank=True, default=0)),
                ('is_first_login', models.IntegerField(default=1)),
                ('activation_string', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'unactivated_account_codes',
            },
        ),
    ]
