# Generated by Django 3.2.8 on 2022-10-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountactivation',
            name='useremail',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
