# Generated by Django 3.2.8 on 2022-10-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts_import', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloomCompanyScrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_scrape', models.IntegerField()),
                ('to_scrape', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bloom_comany_scrape',
            },
        ),
        migrations.CreateModel(
            name='SecDocumentScrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_scrape', models.IntegerField()),
                ('to_scrape', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sec_document_scrape',
            },
        ),
        migrations.CreateModel(
            name='SecLinkScrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_scrape', models.DateTimeField()),
                ('to_scrape', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sec_link_scrape',
            },
        ),
        migrations.CreateModel(
            name='Sec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_link', models.CharField(max_length=500)),
                ('cik', models.CharField(max_length=200, null=True)),
                ('filed_date', models.DateTimeField()),
                ('is_scraped', models.BooleanField(default=False)),
                ('last_scraped', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts_import.organization')),
            ],
            options={
                'db_table': 'sec',
            },
        ),
    ]
