# Generated by Django 3.2.8 on 2022-11-11 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyID', models.CharField(max_length=255)),
                ('keyValue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubContent_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_keyID', models.CharField(max_length=255)),
                ('Sub_keyValue', models.TextField()),
                ('SubKey_Description', models.TextField()),
                ('level_Info', models.IntegerField()),
                ('Content_Key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wikipedia_scrape.content_type')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('image', models.TextField()),
                ('industry_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wikipedia_scrape.industry')),
                ('type_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wikipedia_scrape.type')),
            ],
        ),
        migrations.AddField(
            model_name='content_type',
            name='Info_Key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wikipedia_scrape.information'),
        ),
    ]
